version: 0.2
env:
  exported-variables:
    - CODEBUILD_BUILD_ID
phases:
  install:
    commands:
      - "yum install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.4/terraform_1.2.4_linux_amd64.zip"
      - "unzip terraform_1.2.4_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
  pre_build:
    commands:
      - cd pipelines
      - terraform init
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo pipeline updated `date`
      - aws codepipeline start-pipeline-execution --name tf-test-pipeline