version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.4/terraform_1.2.4_linux_amd64.zip"
      - "unzip terraform_1.2.4_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan -auto-approve
  post_build:
    commands:
      - echo terraform plan completed on `date`